### ISSUE TITLE
a not-quite cosmetic problem in shader handling

### ISSUE THREAD

**Issue by galtgendo** [libretro/bsnes#12]
There's a little bit of code, that while works, it could use a bit of semi-trivial error handling.

In ruby/video/opengl/surface.hpp, you should consider adding `if (fooVertex != -1) ` for all three glEnableVertexAttribArray/glVertexAttribPointer blocks and the three final glDisableVertexAttribArray calls.

Without the condition, the calls fail silently, but why make them in the first place then.

**Comment by rtretiakov** [comment]
This is something that should be posted in the upstream repository. This one is for libretro issues only.

**Comment by galtgendo** [comment]
...
One problem with that: reporting issues on main is restricted to contributors only.

**Comment by galtgendo** [comment]
* contributors -> collaborators
