### ISSUE TITLE
MSU1 enhanced roms not working.

### ISSUE THREAD

**Issue by MapleStoryPSN** [libretro/bsnes#16]
Loading either the rom or the manifest.bml file results in a black screen for all games using MSU1. No problems when loading them up with snes9x or higan (106) cores.

**Comment by negativeExponent** [comment]
ditto. this was known though when i opened this on discord. hope its currently worked on...

**Comment by rtretiakov** [comment]
It's not supported yet but is on the to do list.

**Comment by m4xw** [comment]
Patch for MSU1 fix /shrug (tested on my switch port)
[msu_fix.zip](https://github.com/libretro/bsnes/files/4066220/msu_fix.zip)

**Comment by hizzlekizzle** [comment]
This looks to be fixed so I'll go ahead and close it. If something else comes up, feel free to reopen.
