### ISSUE TITLE
 PPU Fast Mode OFF outputs incorrect resolution

### ISSUE THREAD

**Issue by nfp0** [libretro/bsnes#38]
When the PPU Fast Mode core option is set to OFF, the output resolution is always 512x448 instead of the expected 256x224 which most games use. This ruins the use of almost any CRT shaders as the output is incorrect.

When the PPU Fast Mode core option is set to ON this does not occur and the resolution is output correctly at 256x224 for most games and 512x448 for those specific games that use it.

**Comment by hizzlekizzle** [comment]
I believe this is working as expected/intended. With the fast mode off, it switches to the accuracy PPU from higan.

**Comment by nfp0** [comment]
I'm aware it switches to the accuracy PPU, but is it intended that the accuracy PPU outputs a 448 resolution for 224p software?

**Comment by nfp0** [comment]
I've just now found out (through the Google's cached Byuu bsnes Github issues) that this is indeed intentional.
Had Byuu not closed the issues section from upstream, I wouldn't need to open this issue. Sorry about that.

**Comment by hizzlekizzle** [comment]
No biggie :)
