### ISSUE TITLE
Trying to rewind resets the game

### ISSUE THREAD

**Issue by bleakassassin** [libretro/bsnes#5]
Pressing the rewind button while using the bsnes HD core will cause the current game to reset. This occurs regardless of what button you have rewind set to.

If you have rewind disabled when loading a game and enable it while a game is running with the core, pressing the rewind button will skip you back to the point in the game where you enabled rewind (assuming that point is still within your rewind buffer).

**Comment by rtretiakov** [comment]
Yeah, this is an issue. We're already aware of it and looking at ways to resolve it. If anyone has insight into the fix, they can post it here. There might be something that needs to change at the core level, but I don't know that for sure yet.

**Comment by rtretiakov** [comment]
This should be fixed now.

**Comment by bleakassassin** [comment]
I can't test this to confirm if it's fixed. The core downloaded through "Online Updater" fails to load games, and trying to build it via libretro-super also fails.

Once building issues have been resolved, I'll get back to you on this.

**Comment by bleakassassin** [comment]
It's working now. Thanks!
