### ISSUE TITLE
[Linux] HD Mode 7 does not work

### ISSUE THREAD

**Issue by mmatis** [libretro/bsnes#6]
Regardless of the scaling setting, HD Mode 7 does not work in linux. Using the most recent 9/22 nightly of bsnes_hd_libretro.so. Games play fine, just no fancy hd. Tried getting CLI output, but it just seems to be stuff related to retroarch, not the core itself. Let me know what I can provide to help!

**Comment by rtretiakov** [comment]
I wrote the port on Linux and can't reproduce this issue. Are you sure you have the correct core option combination? The fast mode PPU must be turned on.

**Comment by mmatis** [comment]
Fast Mode PPU is indeed on. Scale factor is 8x. What is the correct core option combination?

Here's what I have in retroarch-core-options.cfg:

```
bsnes_aspect_ratio = "auto"
bsnes_blur_emulation = "ON"
bsnes_chip_hle = "LLE"
bsnes_coprocessor_delayed_sync = "ON"
bsnes_coprocessor_prefer_hle = "ON"
bsnes_cpu_fastmath = "ON"
bsnes_cpu_overclock = "100"
bsnes_crop_overscan = "disabled"
bsnes_dsp_cubic = "ON"
bsnes_dsp_echo_shadow = "ON"
bsnes_dsp_fast = "ON"
bsnes_entropy = "Low"
bsnes_gamma_ramp = "disabled"
bsnes_hotfixes = "ON"
bsnes_mode7_mosaic = "ON"
bsnes_mode7_perspective = "ON"
bsnes_mode7_scale = "8x"
bsnes_mode7_supersample = "ON"
bsnes_ppu_deinterlace = "ON"
bsnes_ppu_fast = "ON"
bsnes_ppu_no_sprite_limit = "ON"
bsnes_ppu_no_vram_blocking = "ON"
bsnes_ppu_show_overscan = "OFF"
bsnes_region = "auto"
bsnes_sa1_overclock = "100"
bsnes_sfx_overclock = "100"
bsnes_superfx_overclock = "100%"
bsnes_violate_accuracy = "disabled"
```

**Comment by rtretiakov** [comment]
Try turning off supersampling.

**Comment by mmatis** [comment]
Ah! That did it.
