### ISSUE TITLE
Naming discrepancy with bsnesHD core and its various assets.

### ISSUE THREAD

**Issue by klepp0906** [libretro/bsnes#7]
Rather than retyping the issue - im just going to reference it here.
https://github.com/libretro/RetroArch/issues/9537

**Comment by rtretiakov** [comment]
The naming has been (hopefully) worked out now, and the core should just be called bsnes.
The battery saves should be compatible but save states probably are not.

**Comment by klepp0906** [comment]
sorry to re-open, but are you saying the bsnes_hd core is now redundant and bsnes_libretro.dll = bsnes_hd_libretro.dll and thus naming of all support folders will be bsnes?
