### ISSUE TITLE
[Feature Request] High Res Blending "Merge" Option

### ISSUE THREAD

**Issue by Awakened0** [libretro/bsnes#8]
Currently there is only a "Blur Emulation" option to blend high res mode transparency effects like in Kirby's Dreamland 3. snes9x has a "Merge" mode, which blends it without the blurriness. It works really well with CRT shaders too since it seems to force the framebuffer down to 256x224 even when high res is active.

**Comment by rtretiakov** [comment]
This is a feature request that would be better suited for the upstream repository. I hope to keep this port as close to upstream as possible, so would like to avoid adding features of this calibre to the libretro port. If it's something byuu wants to do, then I'll be glad to turn it into a core option.

**Comment by Awakened0** [comment]
Ok, thanks! Made a request upstream.
